// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin": {
            "get": {
                "description": "返回管理后台页面的 HTML 内容，需管理员身份验证",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取管理后台页面",
                "responses": {
                    "200": {
                        "description": "管理后台页面 HTML",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "管理后台页面不存在或读取失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/adminGrantPoints": {
            "post": {
                "description": "管理员给用户增加或减少积分\n获取当前登录用户的信息和积分",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "用户管理",
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "description": "积分操作信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/checkConfig": {
            "get": {
                "description": "检查 config.json 是否存在，返回存在状态和跳转路径",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "检查配置文件是否存在",
                "responses": {
                    "200": {
                        "description": "配置状态",
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfigStatus"
                        }
                    }
                }
            }
        },
        "/api/getApiKey": {
            "get": {
                "description": "获取当前配置文件中的 API Key，仅管理员可见",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取当前 API Key",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIKeyResponse"
                        }
                    }
                }
            }
        },
        "/api/saveConfig": {
            "post": {
                "description": "保存系统配置到 config.json，仅允许首次设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "保存系统配置",
                "parameters": [
                    {
                        "description": "系统配置信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.AppConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "保存成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "解析请求体失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "配置文件已存在，不允许修改",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "无效的请求方法",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "保存配置文件失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config.html": {
            "get": {
                "description": "返回系统配置页面的 HTML 内容",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取配置页面",
                "responses": {
                    "200": {
                        "description": "配置页面 HTML",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "配置页面加载失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configurePoints": {
            "post": {
                "description": "为文件设置积分值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "积分配置"
                ],
                "summary": "配置文件积分",
                "parameters": [
                    {
                        "description": "积分配置信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PointConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloadFile": {
            "post": {
                "description": "扣除用户积分并返回文件下载地址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件下载"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "description": "文件信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/generateApiKey": {
            "post": {
                "description": "管理员生成新的 API Key 并保存到配置文件，返回生成的 API Key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "生成新的 API Key",
                "responses": {
                    "200": {
                        "description": "生成成功，返回新的 API Key",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIKeyResponse"
                        }
                    },
                    "405": {
                        "description": "无效的请求方法",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "保存API Key失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "管理员账号未配置",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getFileInfo": {
            "get": {
                "description": "获取文件名称和所需积分",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件下载"
                ],
                "summary": "获取文件信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件URL",
                        "name": "fileUrl",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getPointsList": {
            "get": {
                "description": "获取所有文件的积分配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "积分配置"
                ],
                "summary": "获取积分配置列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getPointsLog": {
            "get": {
                "description": "获取用户积分变更历史记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "积分日志"
                ],
                "summary": "获取积分变更日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名（可选）",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回记录数量限制（默认50）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getUserInfo": {
            "get": {
                "description": "管理员给用户增加或减少积分\n获取当前登录用户的信息和积分",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "用户管理",
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "description": "积分操作信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getUserPoints": {
            "get": {
                "description": "获取指定用户的积分信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户积分"
                ],
                "summary": "获取用户积分",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getUsersList": {
            "get": {
                "description": "获取所有用户及其积分信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.AppConfig": {
            "type": "object",
            "properties": {
                "alist": {
                    "type": "object",
                    "properties": {
                        "host": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "username": {
                            "type": "string"
                        }
                    }
                },
                "api_key": {
                    "description": "独立的 API Key 字段",
                    "type": "string"
                },
                "db_conn": {
                    "type": "string"
                },
                "db_type": {
                    "type": "string"
                },
                "default_points": {
                    "description": "默认积分配置",
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "handlers.APIKeyResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                }
            }
        },
        "handlers.ConfigStatus": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean"
                },
                "redirect": {
                    "type": "string"
                }
            }
        },
        "models.PointConfig": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "description": "积分描述",
                    "type": "string"
                },
                "fileUrl": {
                    "description": "文件路径",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "points": {
                    "description": "积分值",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "积分管理系统API",
	Description:      "提供用户积分管理、积分配置和积分日志查询等功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
