basePath: /api
definitions:
  config.AppConfig:
    properties:
      alist:
        properties:
          host:
            type: string
          password:
            type: string
          username:
            type: string
        type: object
      api_key:
        description: 独立的 API Key 字段
        type: string
      db_conn:
        type: string
      db_type:
        type: string
      default_points:
        description: 默认积分配置
        type: integer
      github_oauth:
        properties:
          client_id:
            type: string
          client_secret:
            type: string
          redirect_uri:
            type: string
        type: object
      google_oauth:
        description: 三方登录配置，均为非必填，未配置则屏蔽对应登录方式
        properties:
          client_id:
            type: string
          client_secret:
            type: string
          redirect_uri:
            type: string
        type: object
      jwt_secret:
        type: string
      password:
        type: string
      port:
        type: integer
      username:
        type: string
      wechat_oauth:
        properties:
          app_secret:
            type: string
          appid:
            type: string
          redirect_uri:
            type: string
        type: object
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  handlers.APIKeyResponse:
    properties:
      api_key:
        type: string
    type: object
  handlers.ConfigStatus:
    properties:
      exists:
        type: boolean
      redirect:
        type: string
    type: object
  models.PointConfig:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        description: 积分描述
        type: string
      fileUrl:
        description: 文件路径
        type: string
      id:
        type: integer
      points:
        description: 积分值
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: 提供用户积分管理、积分配置和积分日志查询等功能
  title: 积分管理系统API
  version: "1.0"
paths:
  /api/checkConfig:
    get:
      description: 检查 config.json 是否存在，返回存在状态和跳转路径
      produces:
      - application/json
      responses:
        "200":
          description: 配置状态
          schema:
            $ref: '#/definitions/handlers.ConfigStatus'
      summary: 检查配置文件是否存在
      tags:
      - 配置管理
  /api/getApiKey:
    get:
      description: 获取当前配置文件中的 API Key，仅管理员可见
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.APIKeyResponse'
      summary: 获取当前 API Key
      tags:
      - 配置管理
  /api/saveConfig:
    post:
      consumes:
      - application/json
      description: 保存系统配置到 config.json，仅允许首次设置
      parameters:
      - description: 系统配置信息
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/config.AppConfig'
      produces:
      - application/json
      responses:
        "200":
          description: 保存成功
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 解析请求体失败
          schema:
            type: string
        "403":
          description: 配置文件已存在，不允许修改
          schema:
            type: string
        "405":
          description: 无效的请求方法
          schema:
            type: string
        "500":
          description: 保存配置文件失败
          schema:
            type: string
      summary: 保存系统配置
      tags:
      - 配置管理
  /config.html:
    get:
      description: 返回系统配置页面的 HTML 内容
      produces:
      - text/html
      responses:
        "200":
          description: 配置页面 HTML
          schema:
            type: string
        "500":
          description: 配置页面加载失败
          schema:
            type: string
      summary: 获取配置页面
      tags:
      - 配置管理
  /configurePoints:
    post:
      consumes:
      - application/json
      description: 为文件设置积分值
      parameters:
      - description: 积分配置信息
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/models.PointConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 配置文件积分
      tags:
      - 积分配置
  /generateApiKey:
    post:
      consumes:
      - application/json
      description: 管理员生成新的 API Key 并保存到配置文件，返回生成的 API Key
      produces:
      - application/json
      responses:
        "200":
          description: 生成成功，返回新的 API Key
          schema:
            $ref: '#/definitions/handlers.APIKeyResponse'
        "405":
          description: 无效的请求方法
          schema:
            type: string
        "500":
          description: 保存API Key失败
          schema:
            type: string
        "503":
          description: 管理员账号未配置
          schema:
            type: string
      summary: 生成新的 API Key
      tags:
      - 配置管理
  /getPointsList:
    get:
      description: 获取所有文件的积分配置
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取积分配置列表
      tags:
      - 积分配置
  /getPointsLog:
    get:
      description: 获取用户积分变更历史记录
      parameters:
      - description: 用户名（可选）
        in: query
        name: username
        type: string
      - description: 返回记录数量限制（默认50）
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取积分变更日志
      tags:
      - 积分日志
  /getUserPoints:
    get:
      description: 获取指定用户的积分信息
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户积分
      tags:
      - 用户积分
  /getUsersList:
    get:
      description: 获取所有用户及其积分信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户列表
      tags:
      - 用户管理
swagger: "2.0"
